version: "3.8"

services: 
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        container_name: elasticsearch1
        environment:
            - node.name=es01
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        restart: always
    
    kibana-dashboard:
        image: docker.elastic.co/kibana/kibana:7.12.1
        volumes:
            - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - 5601:5601
        restart: always
